<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-cart"><?php echo $this->getHeaderText() ?></h4>
        <div class="form-buttons"><button title="Save" type="submit" class="scalable save" onclick="savePaymentMethod()" ><span><span><span>Save</span></span></span></button></div>
    </div>
    <div class="fieldset">
        <?php echo $this->getChild('paymentMethodForm')->setCart($this->getCart())->toHtml() ?>
    </div>
</div>

<script>

function savePaymentMethod(){
    $url = "<?= $this->getUrl('*/*/savePaymentMethod') ?>";
    document.cartForm.action = $url;
}

</script>