<form name="cartForm" method='post' action="<?php echo $this->getUrl('*/*/saveShippingAddress'); ?>" >  
<?php echo $this->getBlockHtml('formkey'); ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-cart"><?php echo $this->getHeaderText() ?></h4>
        <div class="form-buttons"><button title="Save" type="submit" class="scalable save"><span><span><span>Save</span></span></span></button></div>
    </div>
    <div class="fieldset">
        <?php echo $this->getChild('shippingAddressForm')->setCart($this->getCart())->toHtml(); ?>
    </div>
</div>

</form>