<div id="order-totals" class="order-totals">
    <div>
        <table cellspacing="0" cellpadding="8" width="100%">
            <tbody>
                <tr>
                    <td style="" class="a-right" colspan="1">
                        Subtotal    </td>
                    <td style="" class="a-right">
                        <span class="price"><?= $this->getCart()->getCartTotal(); ?></span>    </td>
                </tr>
                <tr>
                    <td style="" class="a-right" colspan="1">
                        Shipping Total    </td>
                    <td style="" class="a-right">
                        <span class="price"><?= $this->getCart()->getShippingAmount(); ?></span>    </td>
                </tr>
                <tr>
                    <td style="" class="a-right" colspan="1">
                        <strong>Grand Total</strong>
                    </td>
                    <td style="" class="a-right">
                        <strong><span class="price"><?= $this->getCart()->getGrandTotal(); ?></span></strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="divider"></div>
        <div class="order-totals-bottom">
            
                <p><button id="id_b41fc707a2c7d1b11f485e2a5ff2e8d8" title="Submit Order" type="submit" class="scalable save" onclick="placeOrder()" style=""><span><span><span>Submit Order</span></span></span></button></p>
        </div>
    </div>
</div>