<?php $shippingAddress = $this->getShippingAddress(); ?>
<?php 
$street  = $shippingAddress->getStreet();
if(is_array($street)){
    $street = $street[0];
}
?>
<?php $countries = $this->getCountries(); ?>

<input type="checkbox" id="shipping_as_billing" name="shipping[shipping_as_billing]" value="1" onchange="disableField()">
<label for="shipping_as_billing" class="no-float">Same As Billing Address</label>

<div class="order-address" id="order-shipping_address_fields">
    <div class="content">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><label for="name">First Name <span class="required">*</span></label></td>
                        <td class="value">
                            <input id="shipping_firstname" name="shipping[firstname]" value="<?php echo $shippingAddress->getFirstname() ?>" class=" required-entry input-text required-entry" type="text" required>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="name">Middle Name</label></td>
                        <td class="value">
                            <input id="shipping_middlename" name="shipping[middlename]" value="<?php echo $shippingAddress->getMiddlename() ?>" class=" input-text" type="text">
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="name">Last Name <span class="required">*</span></label></td>
                        <td class="value">
                            <input id="shipping_lastname" name="shipping[lastname]" value="<?php echo $shippingAddress->getLastname() ?>" class=" required-entry input-text required-entry" type="text" required>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="street">Street <span class="required">*</span></label></td>
                        <td class="value">
                            <div class="multi-input"><input id="shipping_street" name="shipping[street]" value="<?php echo $street ?>" class="input-text required-entry" type="text" required>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="city">City <span class="required">*</span></label></td>
                        <td class="value">
                            <input id="shipping_city" name="shipping[city]" value="<?php echo $shippingAddress->getCity()  ?>" class=" required-entry input-text required-entry" type="text" required>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="state">State <span class="required">*</span></label></td>
                        <td class="value">
                            <input id="shipping_state" name="shipping[state]" value="<?php echo $shippingAddress->getState()  ?>" class=" required-entry input-text required-entry" type="text" required>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="zipcode">Zipcode <span class="required">*</span></label></td>
                        <td class="value">
                            <input id="shipping_zipcode" name="shipping[zipcode]" value="<?php echo $shippingAddress->getZipcode()  ?>" class=" required-entry input-text required-entry" type="text" required>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="country_id">Country <span class="required">*</span></label></td>
                        <td class="value">
                            <select id="shipping_country" name="shipping[country]" class="required-entry required-entry select" required>
                                <?php foreach ($countries as $country) : ?>
                                    <option value="<?php echo $country['value'] ?>" <?php if ($country['value'] == $shippingAddress->getCountry()) : ?>selected<?php endif; ?>><?php echo $country['label'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="order-save-in-address-book">
        <input name="shipping[save_in_shipping_address]" type="checkbox" id="save-in-shipping-address-book" value="1">
        <label for="save-in-shipping-address-book">Save in address book</label>
    </div>

</div>

<script>
function disableField(){
    var shippingAsBilling = document.getElementById('shipping_as_billing');
    if(shippingAsBilling.checked){
        document.getElementById("shipping_firstname").disabled = true;
        document.getElementById("shipping_middlename").disabled = true;
        document.getElementById("shipping_lastname").disabled = true;
        document.getElementById("shipping_street").disabled = true;
        document.getElementById("shipping_city").disabled = true;
        document.getElementById("shipping_state").disabled = true;
        document.getElementById("shipping_country").disabled = true;
        document.getElementById("shipping_zipcode").disabled = true;
    } else {
        document.getElementById("shipping_firstname").disabled = false;
        document.getElementById("shipping_middlename").disabled = false;
        document.getElementById("shipping_lastname").disabled = false;
        document.getElementById("shipping_street").disabled = false;
        document.getElementById("shipping_city").disabled = false;
        document.getElementById("shipping_state").disabled = false;
        document.getElementById("shipping_country").disabled = false;
        document.getElementById("shipping_zipcode").disabled = false;

    }
    
}
</script>