<form action="<?= $this->getUrl('*/*/index') ?>" method="POST">
<?php echo $this->getBlockHtml('formkey'); ?>
<div class="content-header">
    <div id="order-header">
      <div>
        <h3 class="icon-head head-sales-order"><?php echo $this->getHeaderText(); ?></h3>
        <p class="form-buttons"><button id="id_05a1ff8b9270ce1aaf1d6013765c475c" title="Back" type="submit" class="scalable back" style=""><span><span><span>Back</span></span></span></button></p>
      </div>
    </div> 
</div>
</form>

<table style="width: 100%" cellspacing="2">
  	<tbody>

      <tr>
        <td colspan="2" style="padding: 10px">
          <?php echo $this->getChild('orderItem')->setOrder($this->getOrder())->toHtml(); ?>
        </td>
      </tr>	

      <tr>
        <td style="padding: 10px">
           <?php echo $this->getChild('order_account')->setOrder($this->getOrder())->toHtml();?>
        </td>
        <td>
        </td>
      </tr>
  	 
      <tr>
  	  	<td style="padding: 10px" width="50%">
  	      <?php echo $this->getChild('order_billingAddress')->setOrder($this->getOrder())->toHtml(); ?>
  	  	</td>
  	  	<td style="padding: 10px" width="50%">
  	      <?php echo $this->getChild('order_shippingAddress')->setOrder($this->getOrder())->toHtml(); ?>
  	     </td>  		
  	  </tr>
      
       <tr>
        <td>
               <br>
        </td>
      </tr> 
  	
      <tr>
  	  	<td style="padding: 10px">
  	  		<?php echo $this->getChild('order_paymentMethod')->setOrder($this->getOrder())->toHtml(); ?>
  	  	</td> 
         <td style="padding: 10px">
  	  		<?php echo $this->getChild('order_shipmentMethod')->setOrder($this->getOrder())->toHtml(); ?>
  	  	</td>

  	  </tr>
      
       <tr>
        <td>
               <br>
        </td>
      </tr> 
  	 
      <tr>
  	  	<td>
  	  		
  	  	</td>
  	  	<td style="padding: 10px">
  	  		<?php echo $this->getChild('orderTotal')->setOrder($this->getOrder())->toHtml();?>
  	  	</td>
  	  </tr>
  	 </tbody> 
</table>	
