<div id="order-totals" class="order-totals">
    <div>
        <table cellspacing="0" cellpadding="8" width="100%">
            <tbody>
                <tr>
                    <td style="" class="a-right" colspan="1">
                        Subtotal    </td>
                    <td style="" class="a-right">
                        <span class="price">$<?= $this->getOrder()->getOrderTotal(); ?></span>    </td>
                </tr>
                <tr>
                    <td style="" class="a-right" colspan="1">
                        Shipping Total    </td>
                    <td style="" class="a-right">
                        <span class="price">$<?= $this->getOrder()->getShippingAmount(); ?></span>    </td>
                </tr>
                <tr>
                    <td style="" class="a-right" colspan="1">
                        <strong>Grand Total</strong>
                    </td>
                    <td style="" class="a-right">
                        <strong><span class="price">$<?= $this->getOrder()->getGrandTotal(); ?></span></strong>
                    </td>
                </tr>
            </tbody>
        </table>
       
    </div>
</div>